import { ChessPieceType } from "../interfaces";

export const availableMovementsForChessPieceType = {
    [ChessPieceType.PAWN]: [
        {row: 1, column: 0},
        {row: 2, column: 0},
    ],
    [ChessPieceType.ROOK]: [
        // Горизонтальные ходы (вправо)
        {row: 0, column: 1},
        {row: 0, column: 2},
        {row: 0, column: 3},
        {row: 0, column: 4},
        {row: 0, column: 5},
        {row: 0, column: 6},
        {row: 0, column: 7},
        // Горизонтальные ходы (влево)
        {row: 0, column: -1},
        {row: 0, column: -2},
        {row: 0, column: -3},
        {row: 0, column: -4},
        {row: 0, column: -5},
        {row: 0, column: -6},
        {row: 0, column: -7},
        // Вертикальные ходы (вверх)
        {row: 1, column: 0},
        {row: 2, column: 0},
        {row: 3, column: 0},
        {row: 4, column: 0},
        {row: 5, column: 0},
        {row: 6, column: 0},
        {row: 7, column: 0},
        // Вертикальные ходы (вниз)
        {row: -1, column: 0},
        {row: -2, column: 0},
        {row: -3, column: 0},
        {row: -4, column: 0},
        {row: -5, column: 0},
        {row: -6, column: 0},
        {row: -7, column: 0},
    ],
    [ChessPieceType.KNIGHT]: [
        {row: 2, column: 1},
        {row: 2, column: -1},
        {row: -2, column: 1},
        {row: -2, column: -1},
        {row: 1, column: 2},
        {row: 1, column: -2},
        {row: -1, column: 2},
        {row: -1, column: -2},
    ],
    [ChessPieceType.BISHOP]: [
        {row: 1, column: 1},
        {row: 1, column: -1},
        {row: -1, column: 1},
        {row: -1, column: -1},
        {row: 2, column: 2},
        {row: 2, column: -2},
        {row: -2, column: 2},
        {row: -2, column: -2},
        {row: 3, column: 3},
        {row: 3, column: -3},
        {row: -3, column: 3},
        {row: -3, column: -3},
        {row: 4, column: 4},
        {row: 4, column: -4},
        {row: -4, column: 4},
        {row: -4, column: -4},
        {row: 5, column: 5},
        {row: 5, column: -5},
        {row: -5, column: 5},
        {row: -5, column: -5},
        {row: 6, column: 6},
        {row: 6, column: -6},
        {row: -6, column: 6},
        {row: -6, column: -6},
        {row: 7, column: 7},
        {row: 7, column: -7},
        {row: -7, column: 7},
        {row: -7, column: -7},
        {row: 8, column: 8},
        {row: 8, column: -8},
    ],
    [ChessPieceType.QUEEN]: [
        // Горизонтальные ходы (вправо)
        {row: 0, column: 1},
        {row: 0, column: 2},
        {row: 0, column: 3},
        {row: 0, column: 4},
        {row: 0, column: 5},
        {row: 0, column: 6},
        {row: 0, column: 7},
        // Горизонтальные ходы (влево)
        {row: 0, column: -1},
        {row: 0, column: -2},
        {row: 0, column: -3},
        {row: 0, column: -4},
        {row: 0, column: -5},
        {row: 0, column: -6},
        {row: 0, column: -7},
        // Вертикальные ходы (вверх)
        {row: 1, column: 0},
        {row: 2, column: 0},
        {row: 3, column: 0},
        {row: 4, column: 0},
        {row: 5, column: 0},
        {row: 6, column: 0},
        {row: 7, column: 0},
        // Вертикальные ходы (вниз)
        {row: -1, column: 0},
        {row: -2, column: 0},
        {row: -3, column: 0},
        {row: -4, column: 0},
        {row: -5, column: 0},
        {row: -6, column: 0},
        {row: -7, column: 0},
        // Диагональные ходы (вправо-вверх)
        {row: 1, column: 1},
        {row: 2, column: 2},
        {row: 3, column: 3},
        {row: 4, column: 4},
        {row: 5, column: 5},
        {row: 6, column: 6},
        {row: 7, column: 7},
        // Диагональные ходы (влево-вверх)
        {row: 1, column: -1},
        {row: 2, column: -2},
        {row: 3, column: -3},
        {row: 4, column: -4},
        {row: 5, column: -5},
        {row: 6, column: -6},
        {row: 7, column: -7},
        // Диагональные ходы (вправо-вниз)
        {row: -1, column: 1},
        {row: -2, column: 2},
        {row: -3, column: 3},
        {row: -4, column: 4},
        {row: -5, column: 5},
        {row: -6, column: 6},
        {row: -7, column: 7},
        // Диагональные ходы (влево-вниз)
        {row: -1, column: -1},
        {row: -2, column: -2},
        {row: -3, column: -3},
        {row: -4, column: -4},
        {row: -5, column: -5},
        {row: -6, column: -6},
        {row: -7, column: -7},
    ],
    [ChessPieceType.KING]: [
        {row: 1, column: 1},
        {row: 1, column: -1},
        {row: -1, column: 1},
        {row: -1, column: -1},
        {row: 1, column: 0},
        {row: -1, column: 0},
        {row: 0, column: 1},
        {row: 0, column: -1},
    ]   
}